version: '3.8'

services:
  db:
    image: mysql:latest
    volumes:
      - ./init/db_training.sql:/docker-entrypoint-initdb.d/db_training.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: studyCircle

  gui:
    image: adminer
    restart: always
    ports:
      - 8080:8080

